title:             冯兄话吉
email:             fengmengzhao@gmail.com
description:       『格物致知，不可私享；冯兄话吉，载文传享』
author:             冯兄
#baseurl:           "/startbootstrap-clean-blog-jekyll"
baseurl:           ""
url:               "http://fengmengzhao.github.io"

# Social Profiles
twitter_username:  #fengmengzhao
github_username:   FengMengZhao
facebook_username: #fengmengzhao

# 百度统计
analytics:
    baidu:
        siteid: a66e23d778dbfa813dcc8e5ad7b661ec

# Build settings
markdown:          kramdown
highlighter: rouge
paginate:          10 
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
